language: swift
osx_image: xcode10.2
xcode_project: FunctionalTableData.xcodeproj
xcode_scheme: FunctionalTableData
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
notifications:
  disabled: true
